package ship.f.engine.client.core

import ship.f.engine.client.core.ScopeTo.SingleScopeTo

abstract class Event {
    data class InitialEvent(val name: String) : Event() { //I may be making an error with this scope implementation as well... Actually I might be okay
        override fun getScopes(): List<ScopeTo> = listOf(SingleScopeTo(value = name))
    }

    abstract fun getScopes(): List<ScopeTo> // will be generated by KSP
}